services:
  - type: web
    name: school-results-publisher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: school-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: school-db
    plan: free
